apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client #we're telling the deployment to find the pods with label app: comments
  template: #this sets the template.
    metadata:
      labels:
        app: client #For any pod the deployment is going to create it should have the label of app: comments
    spec: #This defines the specifications/configuration of the pod we want to create
      containers:
        - name: client
          image: flairxy/client #auto sets to the latest version
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
