apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts #we're telling the deployment to find the pods with label app: posts
  template: #this sets the template.
    metadata:
      labels:
        app: posts #For any pod the deployment is going to create it should have the label of app: posts
    spec: #This defines the specifications/configuration of the pod we want to create
      containers:
        - name: posts
          image: flairxy/posts #auto sets to the latest version
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector: #This points to the label in the pod
    app: posts
  ports: #This should match the port your app is listening to
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000 #this is the actual port we want to connect to
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
