apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query #we're telling the deployment to find the pods with label app: query
  template: #this sets the template.
    metadata:
      labels:
        app: query #For any pod the deployment is going to create it should have the label of app: query
    spec: #This defines the specifications/configuration of the pod we want to create
      containers:
        - name: query
          image: flairxy/query #auto sets to the latest version
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
